[package]
name = "sequencer"
version = "0.1.0"
authors = ["Yannik Sander <ysander@techfak.uni-bielefeld.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.6"
clap = "2.33"
